# Generated by Django 4.2.18 on 2025-01-20 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='BooleanField',
        ),
        migrations.RemoveField(
            model_name='game',
            name='DecimalField',
        ),
    ]
